"""
core/runtime/sovereign_execution_alignment_engine.py

Sovereign Execution Alignment Engine

Strategic execution validator between:

    sovereign decision fabric
        ↓
    execution alignment
        ↓
    governance approval / execution router / connector fabric

IMPORTANT:
This engine DOES NOT execute actions.

It does NOT:
- call Microsoft Graph
- isolate endpoints
- revoke sessions
- quarantine mailboxes
- delete emails
- mutate external systems

It ONLY determines:
- whether execution should proceed
- under what governance conditions
- whether approval is required
- whether rollback/continuity review is required
- whether the action must be blocked or deferred
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Sequence


# ============================================================
# CONSTANTS
# ============================================================

SEVERITY_INFO = "INFO"
SEVERITY_LOW = "LOW"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"
SEVERITY_CRITICAL = "CRITICAL"

BLAST_RADIUS_LOW = "LOW"
BLAST_RADIUS_MEDIUM = "MEDIUM"
BLAST_RADIUS_HIGH = "HIGH"
BLAST_RADIUS_CRITICAL = "CRITICAL"

ALIGNMENT_ALLOWED = "ALLOWED"
ALIGNMENT_ALLOWED_WITH_GOVERNANCE = "ALLOWED_WITH_GOVERNANCE"
ALIGNMENT_ALLOWED_WITH_APPROVAL = "ALLOWED_WITH_APPROVAL"
ALIGNMENT_BLOCKED = "BLOCKED"
ALIGNMENT_DEFERRED = "DEFERRED"
ALIGNMENT_REQUIRES_CONTINUITY_REVIEW = "REQUIRES_CONTINUITY_REVIEW"
ALIGNMENT_REQUIRES_ROLLBACK_PLAN = "REQUIRES_ROLLBACK_PLAN"

DEFAULT_ENGINE_NAME = "sovereign_execution_alignment_engine"


class AutonomyMode(str, Enum):
    MANUAL = "MANUAL"
    ASSISTED = "ASSISTED"
    SUPERVISED_AUTONOMY = "SUPERVISED_AUTONOMY"
    FULL_AUTONOMY = "FULL_AUTONOMY"
    LOCKDOWN = "LOCKDOWN"


class ExecutionActionType(str, Enum):
    OBSERVE = "OBSERVE"
    INVESTIGATE = "INVESTIGATE"
    ENRICH = "ENRICH"
    ESCALATE = "ESCALATE"
    NOTIFY = "NOTIFY"
    CONTAIN = "CONTAIN"
    ISOLATE_ENDPOINT = "ISOLATE_ENDPOINT"
    REVOKE_SESSION = "REVOKE_SESSION"
    DISABLE_USER = "DISABLE_USER"
    QUARANTINE_EMAIL = "QUARANTINE_EMAIL"
    DELETE_EMAIL = "DELETE_EMAIL"
    PURGE_MAILBOX = "PURGE_MAILBOX"
    BLOCK_NETWORK_TRAFFIC = "BLOCK_NETWORK_TRAFFIC"
    UPDATE_POLICY = "UPDATE_POLICY"
    ROLLBACK = "ROLLBACK"
    UNKNOWN = "UNKNOWN"


class AlignmentDomain(str, Enum):
    RUNTIME = "RUNTIME"
    GOVERNANCE = "GOVERNANCE"
    SECURITY = "SECURITY"
    CONTINUITY = "CONTINUITY"
    CASES = "CASES"
    COMPLIANCE = "COMPLIANCE"
    FEDRAMP = "FEDRAMP"
    CMMC = "CMMC"
    NETWORK = "NETWORK"
    IDENTITY = "IDENTITY"
    EMAIL = "EMAIL"
    ENDPOINT = "ENDPOINT"
    UNKNOWN = "UNKNOWN"


# ============================================================
# DATA MODELS
# ============================================================

@dataclass(frozen=True)
class SovereignExecutionAlignmentRequest:
    """
    Normalized request for execution alignment.

    This may be created directly or derived from a route plan generated by:
        sovereign_decision_fabric.py
    """

    alignment_request_id: str
    source_plan_id: Optional[str]
    source_engine: str
    action_type: str
    domain: str
    severity: str
    confidence: float
    mission_priority: int
    summary: str

    tenant_id: Optional[str] = None
    case_id: Optional[str] = None
    correlation_id: Optional[str] = None

    payload: Dict[str, Any] = field(default_factory=dict)

    requires_governance: bool = False
    requires_human_approval: bool = False
    requires_legal_approval: bool = False
    requires_export_control_review: bool = False
    requires_rollback_plan: bool = False
    rollback_available: bool = False
    verification_required: bool = True
    continuity_sensitive: bool = False
    affects_privileged_identity: bool = False
    affects_mission_critical_asset: bool = False
    allow_autonomous_execution: bool = False

    created_at_ms: int = field(default_factory=lambda: int(time.time() * 1000))


@dataclass(frozen=True)
class SovereignExecutionAlignmentVerdict:
    """
    Final alignment verdict.

    This is NOT an execution result.
    """

    verdict_id: str
    alignment_request_id: Optional[str]
    source_plan_id: Optional[str]
    verdict: str
    action_type: str
    domain: str
    severity: str
    confidence: float
    mission_priority: int
    blast_radius: str
    autonomy_mode: str

    allowed: bool
    blocked: bool
    governance_required: bool
    human_approval_required: bool
    legal_approval_required: bool
    export_control_review_required: bool
    rollback_plan_required: bool
    continuity_review_required: bool
    verification_required: bool

    rationale: str
    constraints: List[str]
    required_controls: List[str]
    recommended_next_steps: List[Dict[str, Any]]

    tenant_id: Optional[str] = None
    case_id: Optional[str] = None
    correlation_id: Optional[str] = None

    created_at_ms: int = field(default_factory=lambda: int(time.time() * 1000))


@dataclass(frozen=True)
class SovereignExecutionAlignmentSnapshot:
    """
    Lightweight diagnostics snapshot.
    """

    engine_name: str
    autonomy_mode: str
    total_requests_seen: int
    total_verdicts_created: int
    last_verdict_id: Optional[str]
    last_verdict: Optional[str]
    last_blast_radius: Optional[str]
    last_updated_ms: int


# ============================================================
# ENGINE
# ============================================================

class SovereignExecutionAlignmentEngine:
    """
    Strategic alignment layer for autonomous execution safety.

    Design guarantees:
    - no connector execution
    - no external side effects except optional event/memory/lineage writes
    - deterministic verdict generation
    - explicit dependency injection
    - append-only local verdict history
    """

    def __init__(
        self,
        *,
        engine_name: str = DEFAULT_ENGINE_NAME,
        autonomy_mode: str = AutonomyMode.SUPERVISED_AUTONOMY.value,
        event_bus: Optional[Any] = None,
        operational_memory_engine: Optional[Any] = None,
        governance_engine: Optional[Any] = None,
        lineage_engine: Optional[Any] = None,
        continuity_engine: Optional[Any] = None,
    ) -> None:
        self.engine_name = engine_name
        self.autonomy_mode = self._safe_autonomy_mode(autonomy_mode)

        self.event_bus = event_bus
        self.operational_memory_engine = operational_memory_engine
        self.governance_engine = governance_engine
        self.lineage_engine = lineage_engine
        self.continuity_engine = continuity_engine

        self._requests_seen = 0
        self._verdicts: List[SovereignExecutionAlignmentVerdict] = []

    # --------------------------------------------------------
    # PUBLIC API
    # --------------------------------------------------------

    def align(
        self,
        request: SovereignExecutionAlignmentRequest | Dict[str, Any],
        *,
        context: Optional[Dict[str, Any]] = None,
    ) -> SovereignExecutionAlignmentVerdict:
        """
        Align one execution request and return a deterministic verdict.
        """

        normalized = self._normalize_request(request)
        self._requests_seen += 1

        blast_radius = self._estimate_blast_radius(normalized)
        constraints = self._evaluate_constraints(normalized, blast_radius)
        verdict_value = self._determine_verdict(
            normalized,
            blast_radius,
            constraints,
        )

        verdict = SovereignExecutionAlignmentVerdict(
            verdict_id=str(uuid.uuid4()),
            alignment_request_id=normalized.alignment_request_id,
            source_plan_id=normalized.source_plan_id,
            verdict=verdict_value,
            action_type=normalized.action_type,
            domain=normalized.domain,
            severity=normalized.severity,
            confidence=normalized.confidence,
            mission_priority=normalized.mission_priority,
            blast_radius=blast_radius,
            autonomy_mode=self.autonomy_mode,
            allowed=self._is_allowed(verdict_value),
            blocked=(verdict_value == ALIGNMENT_BLOCKED),
            governance_required=self._requires_governance(
                normalized,
                verdict_value,
            ),
            human_approval_required=self._requires_human_approval(
                normalized,
                verdict_value,
                blast_radius,
            ),
            legal_approval_required=(
                normalized.requires_legal_approval
                or normalized.action_type
                in {
                    ExecutionActionType.PURGE_MAILBOX.value,
                    ExecutionActionType.DELETE_EMAIL.value,
                }
            ),
            export_control_review_required=(
                normalized.requires_export_control_review
            ),
            rollback_plan_required=self._requires_rollback_plan(
                normalized,
                verdict_value,
                blast_radius,
            ),
            continuity_review_required=(
                verdict_value
                == ALIGNMENT_REQUIRES_CONTINUITY_REVIEW
            ),
            verification_required=normalized.verification_required,
            rationale=self._build_rationale(
                normalized,
                verdict_value,
                blast_radius,
                constraints,
            ),
            constraints=constraints,
            required_controls=self._required_controls(
                normalized,
                verdict_value,
                blast_radius,
            ),
            recommended_next_steps=self._recommended_next_steps(
                normalized,
                verdict_value,
                blast_radius,
            ),
            tenant_id=normalized.tenant_id,
            case_id=normalized.case_id,
            correlation_id=normalized.correlation_id,
        )

        self._record_verdict(verdict, context=context)
        return verdict

    def align_route_plan(
        self,
        route_plan: Any,
        *,
        context: Optional[Dict[str, Any]] = None,
    ) -> SovereignExecutionAlignmentVerdict:
        """
        Accept a SovereignDecisionRoutePlan or compatible dict
        from sovereign_decision_fabric.py.
        """

        request = self._request_from_route_plan(route_plan)
        return self.align(request, context=context)

    def submit(
        self,
        item: SovereignExecutionAlignmentRequest | Dict[str, Any],
        *,
        context: Optional[Dict[str, Any]] = None,
    ) -> SovereignExecutionAlignmentVerdict:
        """
        Compatibility alias for handoff-style integrations.
        """

        return self.align(item, context=context)

    def create_request(
        self,
        *,
        source_engine: str,
        action_type: str,
        domain: str,
        severity: str,
        confidence: float,
        mission_priority: int,
        summary: str,
        source_plan_id: Optional[str] = None,
        tenant_id: Optional[str] = None,
        case_id: Optional[str] = None,
        correlation_id: Optional[str] = None,
        payload: Optional[Dict[str, Any]] = None,
        requires_governance: bool = False,
        requires_human_approval: bool = False,
        requires_legal_approval: bool = False,
        requires_export_control_review: bool = False,
        requires_rollback_plan: bool = False,
        rollback_available: bool = False,
        verification_required: bool = True,
        continuity_sensitive: bool = False,
        affects_privileged_identity: bool = False,
        affects_mission_critical_asset: bool = False,
        allow_autonomous_execution: bool = False,
    ) -> SovereignExecutionAlignmentRequest:
        """
        Convenience constructor.
        """

        return SovereignExecutionAlignmentRequest(
            alignment_request_id=str(uuid.uuid4()),
            source_plan_id=source_plan_id,
            source_engine=source_engine or "unknown_engine",
            action_type=self._safe_action_type(action_type),
            domain=self._safe_domain(domain),
            severity=self._safe_severity(severity),
            confidence=self._clamp_confidence(confidence),
            mission_priority=max(0, int(mission_priority)),
            summary=summary or "",
            tenant_id=tenant_id,
            case_id=case_id,
            correlation_id=correlation_id,
            payload=payload or {},
            requires_governance=requires_governance,
            requires_human_approval=requires_human_approval,
            requires_legal_approval=requires_legal_approval,
            requires_export_control_review=requires_export_control_review,
            requires_rollback_plan=requires_rollback_plan,
            rollback_available=rollback_available,
            verification_required=verification_required,
            continuity_sensitive=continuity_sensitive,
            affects_privileged_identity=affects_privileged_identity,
            affects_mission_critical_asset=affects_mission_critical_asset,
            allow_autonomous_execution=allow_autonomous_execution,
        )

    def get_recent_verdicts(
        self,
        *,
        limit: int = 25,
    ) -> List[SovereignExecutionAlignmentVerdict]:
        """
        Return recent verdicts newest-first.
        """

        limit = max(1, int(limit))
        return list(reversed(self._verdicts[-limit:]))

    def snapshot(self) -> SovereignExecutionAlignmentSnapshot:
        """
        Return lightweight engine state.
        """

        last = self._verdicts[-1] if self._verdicts else None

        return SovereignExecutionAlignmentSnapshot(
            engine_name=self.engine_name,
            autonomy_mode=self.autonomy_mode,
            total_requests_seen=self._requests_seen,
            total_verdicts_created=len(self._verdicts),
            last_verdict_id=last.verdict_id if last else None,
            last_verdict=last.verdict if last else None,
            last_blast_radius=last.blast_radius if last else None,
            last_updated_ms=int(time.time() * 1000),
        )

    # --------------------------------------------------------
    # VERDICT LOGIC
    # --------------------------------------------------------

    def _determine_verdict(
        self,
        request: SovereignExecutionAlignmentRequest,
        blast_radius: str,
        constraints: Sequence[str],
    ) -> str:
        """
        Deterministic verdict generation.
        """

        if self.autonomy_mode == AutonomyMode.LOCKDOWN.value:
            return ALIGNMENT_BLOCKED

        if "BLOCKED_ACTION_TYPE" in constraints:
            return ALIGNMENT_BLOCKED

        if "CONTINUITY_REVIEW_REQUIRED" in constraints:
            return ALIGNMENT_REQUIRES_CONTINUITY_REVIEW

        if "ROLLBACK_PLAN_REQUIRED" in constraints:
            return ALIGNMENT_REQUIRES_ROLLBACK_PLAN

        if request.requires_human_approval:
            return ALIGNMENT_ALLOWED_WITH_APPROVAL

        if request.requires_legal_approval:
            return ALIGNMENT_ALLOWED_WITH_APPROVAL

        if request.requires_export_control_review:
            return ALIGNMENT_ALLOWED_WITH_GOVERNANCE

        if request.requires_governance:
            return ALIGNMENT_ALLOWED_WITH_GOVERNANCE

        if self.autonomy_mode == AutonomyMode.MANUAL.value:
            return ALIGNMENT_ALLOWED_WITH_APPROVAL

        if self.autonomy_mode == AutonomyMode.ASSISTED.value:
            return ALIGNMENT_DEFERRED

        if blast_radius in {BLAST_RADIUS_HIGH, BLAST_RADIUS_CRITICAL}:
            if not request.allow_autonomous_execution:
                return ALIGNMENT_ALLOWED_WITH_APPROVAL

        return ALIGNMENT_ALLOWED

    def _evaluate_constraints(
        self,
        request: SovereignExecutionAlignmentRequest,
        blast_radius: str,
    ) -> List[str]:
        """
        Evaluate alignment constraints.
        """

        constraints: List[str] = []

        if request.action_type in {
            ExecutionActionType.PURGE_MAILBOX.value,
            ExecutionActionType.DELETE_EMAIL.value,
        }:
            constraints.append("LEGAL_REVIEW_RECOMMENDED")

        if request.action_type == ExecutionActionType.UPDATE_POLICY.value:
            constraints.append("GOVERNANCE_REVIEW_RECOMMENDED")

        if request.action_type == ExecutionActionType.UNKNOWN.value:
            constraints.append("BLOCKED_ACTION_TYPE")

        if request.affects_mission_critical_asset:
            constraints.append("MISSION_CRITICAL_ASSET")

        if request.affects_privileged_identity:
            constraints.append("PRIVILEGED_IDENTITY")

        if request.continuity_sensitive:
            constraints.append("CONTINUITY_SENSITIVE")

        if (
            request.affects_mission_critical_asset
            and blast_radius in {BLAST_RADIUS_HIGH, BLAST_RADIUS_CRITICAL}
        ):
            constraints.append("CONTINUITY_REVIEW_REQUIRED")

        if (
            request.requires_rollback_plan
            and not request.rollback_available
        ):
            constraints.append("ROLLBACK_PLAN_REQUIRED")

        if (
            blast_radius in {BLAST_RADIUS_HIGH, BLAST_RADIUS_CRITICAL}
            and request.action_type
            not in {
                ExecutionActionType.OBSERVE.value,
                ExecutionActionType.INVESTIGATE.value,
                ExecutionActionType.ENRICH.value,
                ExecutionActionType.NOTIFY.value,
                ExecutionActionType.ESCALATE.value,
            }
            and not request.rollback_available
        ):
            constraints.append("ROLLBACK_PLAN_REQUIRED")

        return constraints

    def _estimate_blast_radius(
        self,
        request: SovereignExecutionAlignmentRequest,
    ) -> str:
        """
        Estimate blast radius from action/domain/risk flags.

        This is deterministic and conservative.
        """

        action = request.action_type

        if request.affects_mission_critical_asset:
            return BLAST_RADIUS_CRITICAL

        if action in {
            ExecutionActionType.PURGE_MAILBOX.value,
            ExecutionActionType.UPDATE_POLICY.value,
        }:
            return BLAST_RADIUS_CRITICAL

        if action in {
            ExecutionActionType.DISABLE_USER.value,
            ExecutionActionType.BLOCK_NETWORK_TRAFFIC.value,
        }:
            return BLAST_RADIUS_HIGH

        if action in {
            ExecutionActionType.ISOLATE_ENDPOINT.value,
            ExecutionActionType.REVOKE_SESSION.value,
            ExecutionActionType.DELETE_EMAIL.value,
        }:
            return BLAST_RADIUS_MEDIUM

        if action in {
            ExecutionActionType.CONTAIN.value,
            ExecutionActionType.QUARANTINE_EMAIL.value,
            ExecutionActionType.ROLLBACK.value,
        }:
            return BLAST_RADIUS_MEDIUM

        if action in {
            ExecutionActionType.OBSERVE.value,
            ExecutionActionType.INVESTIGATE.value,
            ExecutionActionType.ENRICH.value,
            ExecutionActionType.ESCALATE.value,
            ExecutionActionType.NOTIFY.value,
        }:
            return BLAST_RADIUS_LOW

        return BLAST_RADIUS_MEDIUM

    # --------------------------------------------------------
    # REQUIREMENT FLAGS
    # --------------------------------------------------------

    @staticmethod
    def _is_allowed(verdict: str) -> bool:
        return verdict in {
            ALIGNMENT_ALLOWED,
            ALIGNMENT_ALLOWED_WITH_GOVERNANCE,
            ALIGNMENT_ALLOWED_WITH_APPROVAL,
        }

    def _requires_governance(
        self,
        request: SovereignExecutionAlignmentRequest,
        verdict: str,
    ) -> bool:
        return (
            request.requires_governance
            or request.requires_export_control_review
            or verdict == ALIGNMENT_ALLOWED_WITH_GOVERNANCE
        )

    def _requires_human_approval(
        self,
        request: SovereignExecutionAlignmentRequest,
        verdict: str,
        blast_radius: str,
    ) -> bool:
        return (
            request.requires_human_approval
            or request.requires_legal_approval
            or verdict == ALIGNMENT_ALLOWED_WITH_APPROVAL
            or self.autonomy_mode == AutonomyMode.MANUAL.value
            or blast_radius == BLAST_RADIUS_CRITICAL
        )

    @staticmethod
    def _requires_rollback_plan(
        request: SovereignExecutionAlignmentRequest,
        verdict: str,
        blast_radius: str,
    ) -> bool:
        return (
            request.requires_rollback_plan
            or verdict == ALIGNMENT_REQUIRES_ROLLBACK_PLAN
            or blast_radius in {BLAST_RADIUS_HIGH, BLAST_RADIUS_CRITICAL}
        )

    # --------------------------------------------------------
    # RECOMMENDATIONS / CONTROLS
    # --------------------------------------------------------

    def _required_controls(
        self,
        request: SovereignExecutionAlignmentRequest,
        verdict: str,
        blast_radius: str,
    ) -> List[str]:
        controls: List[str] = []

        if verdict == ALIGNMENT_BLOCKED:
            controls.append("block_execution_handoff")

        if self._requires_governance(request, verdict):
            controls.append("governance_review")

        if self._requires_human_approval(request, verdict, blast_radius):
            controls.append("human_approval")

        if request.requires_legal_approval:
            controls.append("legal_approval")

        if request.requires_export_control_review:
            controls.append("export_control_review")

        if self._requires_rollback_plan(request, verdict, blast_radius):
            controls.append("rollback_plan")

        if request.verification_required:
            controls.append("post_execution_verification")

        if verdict == ALIGNMENT_REQUIRES_CONTINUITY_REVIEW:
            controls.append("continuity_review")

        if request.affects_privileged_identity:
            controls.append("privileged_identity_review")

        if request.affects_mission_critical_asset:
            controls.append("mission_critical_asset_review")

        return list(dict.fromkeys(controls))

    def _recommended_next_steps(
        self,
        request: SovereignExecutionAlignmentRequest,
        verdict: str,
        blast_radius: str,
    ) -> List[Dict[str, Any]]:
        steps: List[Dict[str, Any]] = []

        if verdict == ALIGNMENT_BLOCKED:
            steps.append(
                {
                    "step": "do_not_execute",
                    "reason": "Alignment verdict blocked execution handoff.",
                }
            )
            return steps

        if verdict == ALIGNMENT_DEFERRED:
            steps.append(
                {
                    "step": "defer_for_operator_review",
                    "reason": "Autonomy mode requires assisted review.",
                }
            )

        if verdict == ALIGNMENT_ALLOWED_WITH_GOVERNANCE:
            steps.append(
                {
                    "step": "route_to_governance",
                    "reason": "Governance review required before handoff.",
                }
            )

        if verdict == ALIGNMENT_ALLOWED_WITH_APPROVAL:
            steps.append(
                {
                    "step": "create_approval_request",
                    "reason": "Human approval required before handoff.",
                }
            )

        if verdict == ALIGNMENT_REQUIRES_CONTINUITY_REVIEW:
            steps.append(
                {
                    "step": "perform_continuity_review",
                    "reason": "Action may affect mission continuity.",
                }
            )

        if verdict == ALIGNMENT_REQUIRES_ROLLBACK_PLAN:
            steps.append(
                {
                    "step": "attach_rollback_plan",
                    "reason": "Rollback readiness is required before handoff.",
                }
            )

        if verdict == ALIGNMENT_ALLOWED:
            steps.append(
                {
                    "step": "ready_for_execution_router",
                    "reason": "Alignment checks passed.",
                }
            )

        if request.verification_required:
            steps.append(
                {
                    "step": "require_post_execution_verification",
                    "reason": "Verification is required for audit defensibility.",
                }
            )

        steps.append(
            {
                "step": "record_alignment_lineage",
                "reason": (
                    "Verdict should be retained for replayable "
                    "governance and FedRAMP/CMMC evidence lineage."
                ),
            }
        )

        steps.append(
            {
                "step": "blast_radius_recorded",
                "blast_radius": blast_radius,
            }
        )

        return steps

    def _build_rationale(
        self,
        request: SovereignExecutionAlignmentRequest,
        verdict: str,
        blast_radius: str,
        constraints: Sequence[str],
    ) -> str:
        return (
            f"Alignment request from {request.source_engine} for action "
            f"{request.action_type} in domain {request.domain} evaluated "
            f"under autonomy mode {self.autonomy_mode}. Severity "
            f"{request.severity}, confidence {request.confidence:.2f}, "
            f"mission priority {request.mission_priority}, blast radius "
            f"{blast_radius}. Verdict: {verdict}. Constraints: "
            f"{', '.join(constraints) if constraints else 'none'}."
        )

    # --------------------------------------------------------
    # ROUTE PLAN ADAPTER
    # --------------------------------------------------------

    def _request_from_route_plan(
        self,
        route_plan: Any,
    ) -> SovereignExecutionAlignmentRequest:
        """
        Convert SovereignDecisionRoutePlan or dict into alignment request.
        """

        if isinstance(route_plan, dict):
            get = route_plan.get
        else:
            get = lambda key, default=None: getattr(route_plan, key, default)

        selected_intent = str(get("selected_intent", "") or "")
        action_type = self._action_from_intent(selected_intent)

        return SovereignExecutionAlignmentRequest(
            alignment_request_id=str(uuid.uuid4()),
            source_plan_id=get("route_plan_id"),
            source_engine=str(
                get("selected_source_engine", "sovereign_decision_fabric")
                or "sovereign_decision_fabric"
            ),
            action_type=action_type,
            domain=self._domain_from_source(get("selected_source")),
            severity=self._safe_severity(get("severity")),
            confidence=self._clamp_confidence(get("confidence", 0.0)),
            mission_priority=max(
                0,
                int(get("mission_priority", 0) or 0),
            ),
            summary=str(get("rationale", "") or ""),
            tenant_id=get("tenant_id"),
            case_id=get("case_id"),
            correlation_id=get("correlation_id"),
            payload={
                "route_plan": (
                    dict(route_plan)
                    if isinstance(route_plan, dict)
                    else route_plan
                )
            },
            requires_governance=bool(get("governance_required", False)),
            requires_human_approval=bool(
                get("human_approval_required", False)
            ),
            requires_rollback_plan=False,
            rollback_available=False,
            verification_required=True,
            continuity_sensitive=False,
            allow_autonomous_execution=False,
        )

    @staticmethod
    def _action_from_intent(intent: str) -> str:
        intent = str(intent or "").upper()

        mapping = {
            "OBSERVE": ExecutionActionType.OBSERVE.value,
            "RECOMMEND": ExecutionActionType.INVESTIGATE.value,
            "PRIORITIZE": ExecutionActionType.INVESTIGATE.value,
            "ALIGN": ExecutionActionType.INVESTIGATE.value,
            "ESCALATE": ExecutionActionType.ESCALATE.value,
            "CONTAIN": ExecutionActionType.CONTAIN.value,
            "INVESTIGATE": ExecutionActionType.INVESTIGATE.value,
            "REQUEST_APPROVAL": ExecutionActionType.ESCALATE.value,
            "BLOCK": ExecutionActionType.UNKNOWN.value,
            "RECORD": ExecutionActionType.OBSERVE.value,
            "EXECUTION_HANDOFF": ExecutionActionType.INVESTIGATE.value,
        }

        return mapping.get(intent, ExecutionActionType.INVESTIGATE.value)

    def _domain_from_source(
        self,
        source: Any,
    ) -> str:
        value = str(source or "").upper()

        mapping = {
            "COGNITION": AlignmentDomain.RUNTIME.value,
            "COORDINATION": AlignmentDomain.RUNTIME.value,
            "CONTINUITY": AlignmentDomain.CONTINUITY.value,
            "GOVERNANCE": AlignmentDomain.GOVERNANCE.value,
            "MEMORY": AlignmentDomain.RUNTIME.value,
            "CASE": AlignmentDomain.CASES.value,
            "COMPLIANCE": AlignmentDomain.COMPLIANCE.value,
            "SECURITY": AlignmentDomain.SECURITY.value,
            "NETWORK": AlignmentDomain.NETWORK.value,
        }

        return mapping.get(value, AlignmentDomain.UNKNOWN.value)

    # --------------------------------------------------------
    # RECORDING / EVENTS
    # --------------------------------------------------------

    def _record_verdict(
        self,
        verdict: SovereignExecutionAlignmentVerdict,
        *,
        context: Optional[Dict[str, Any]] = None,
    ) -> None:
        self._verdicts.append(verdict)

        self._write_to_operational_memory(verdict, context=context)
        self._write_to_lineage(verdict, context=context)
        self._emit_event(verdict, context=context)

    def _write_to_operational_memory(
        self,
        verdict: SovereignExecutionAlignmentVerdict,
        *,
        context: Optional[Dict[str, Any]] = None,
    ) -> None:
        memory = self.operational_memory_engine
        if memory is None:
            return

        payload = {
            "type": "SOVEREIGN_EXECUTION_ALIGNMENT_VERDICT",
            "verdict": self._verdict_to_dict(verdict),
            "context": context or {},
        }

        try:
            if hasattr(memory, "append_memory"):
                memory.append_memory(payload)
            elif hasattr(memory, "record"):
                memory.record(payload)
            elif hasattr(memory, "write"):
                memory.write(payload)
        except Exception as exc:
            print(f"⚠️ Execution alignment memory write failed: {exc}")

    def _write_to_lineage(
        self,
        verdict: SovereignExecutionAlignmentVerdict,
        *,
        context: Optional[Dict[str, Any]] = None,
    ) -> None:
        lineage = self.lineage_engine
        if lineage is None:
            return

        payload = {
            "type": "SOVEREIGN_EXECUTION_ALIGNMENT_VERDICT",
            "verdict": self._verdict_to_dict(verdict),
            "context": context or {},
        }

        try:
            if hasattr(lineage, "record_lineage"):
                lineage.record_lineage(payload)
            elif hasattr(lineage, "append_lineage"):
                lineage.append_lineage(payload)
            elif hasattr(lineage, "record"):
                lineage.record(payload)
        except Exception as exc:
            print(f"⚠️ Execution alignment lineage write failed: {exc}")

    def _emit_event(
        self,
        verdict: SovereignExecutionAlignmentVerdict,
        *,
        context: Optional[Dict[str, Any]] = None,
    ) -> None:
        if self.event_bus is None:
            return

        payload = {
            "event_type": "SOVEREIGN_EXECUTION_ALIGNMENT_VERDICT",
            "engine": self.engine_name,
            "verdict": self._verdict_to_dict(verdict),
            "context": context or {},
        }

        try:
            if hasattr(self.event_bus, "emit"):
                self.event_bus.emit(
                    "SOVEREIGN_EXECUTION_ALIGNMENT_VERDICT",
                    payload,
                )
            elif hasattr(self.event_bus, "publish"):
                self.event_bus.publish(
                    "SOVEREIGN_EXECUTION_ALIGNMENT_VERDICT",
                    payload,
                )
        except Exception as exc:
            print(f"⚠️ Execution alignment event emit failed: {exc}")

    # --------------------------------------------------------
    # NORMALIZATION / SERIALIZATION
    # --------------------------------------------------------

    def _normalize_request(
        self,
        request: SovereignExecutionAlignmentRequest | Dict[str, Any],
    ) -> SovereignExecutionAlignmentRequest:
        if isinstance(request, SovereignExecutionAlignmentRequest):
            return request

        return SovereignExecutionAlignmentRequest(
            alignment_request_id=str(
                request.get("alignment_request_id") or uuid.uuid4()
            ),
            source_plan_id=request.get("source_plan_id"),
            source_engine=str(request.get("source_engine") or "unknown_engine"),
            action_type=self._safe_action_type(request.get("action_type")),
            domain=self._safe_domain(request.get("domain")),
            severity=self._safe_severity(request.get("severity")),
            confidence=self._clamp_confidence(request.get("confidence", 0.0)),
            mission_priority=max(
                0,
                int(request.get("mission_priority", 0) or 0),
            ),
            summary=str(request.get("summary") or ""),
            tenant_id=request.get("tenant_id"),
            case_id=request.get("case_id"),
            correlation_id=request.get("correlation_id"),
            payload=dict(request.get("payload") or {}),
            requires_governance=bool(
                request.get("requires_governance", False)
            ),
            requires_human_approval=bool(
                request.get("requires_human_approval", False)
            ),
            requires_legal_approval=bool(
                request.get("requires_legal_approval", False)
            ),
            requires_export_control_review=bool(
                request.get("requires_export_control_review", False)
            ),
            requires_rollback_plan=bool(
                request.get("requires_rollback_plan", False)
            ),
            rollback_available=bool(
                request.get("rollback_available", False)
            ),
            verification_required=bool(
                request.get("verification_required", True)
            ),
            continuity_sensitive=bool(
                request.get("continuity_sensitive", False)
            ),
            affects_privileged_identity=bool(
                request.get("affects_privileged_identity", False)
            ),
            affects_mission_critical_asset=bool(
                request.get("affects_mission_critical_asset", False)
            ),
            allow_autonomous_execution=bool(
                request.get("allow_autonomous_execution", False)
            ),
        )

    @staticmethod
    def _verdict_to_dict(
        verdict: SovereignExecutionAlignmentVerdict,
    ) -> Dict[str, Any]:
        return {
            "verdict_id": verdict.verdict_id,
            "alignment_request_id": verdict.alignment_request_id,
            "source_plan_id": verdict.source_plan_id,
            "verdict": verdict.verdict,
            "action_type": verdict.action_type,
            "domain": verdict.domain,
            "severity": verdict.severity,
            "confidence": verdict.confidence,
            "mission_priority": verdict.mission_priority,
            "blast_radius": verdict.blast_radius,
            "autonomy_mode": verdict.autonomy_mode,
            "allowed": verdict.allowed,
            "blocked": verdict.blocked,
            "governance_required": verdict.governance_required,
            "human_approval_required": verdict.human_approval_required,
            "legal_approval_required": verdict.legal_approval_required,
            "export_control_review_required": (
                verdict.export_control_review_required
            ),
            "rollback_plan_required": verdict.rollback_plan_required,
            "continuity_review_required": (
                verdict.continuity_review_required
            ),
            "verification_required": verdict.verification_required,
            "rationale": verdict.rationale,
            "constraints": list(verdict.constraints),
            "required_controls": list(verdict.required_controls),
            "recommended_next_steps": list(verdict.recommended_next_steps),
            "tenant_id": verdict.tenant_id,
            "case_id": verdict.case_id,
            "correlation_id": verdict.correlation_id,
            "created_at_ms": verdict.created_at_ms,
        }

    # --------------------------------------------------------
    # SAFETY HELPERS
    # --------------------------------------------------------

    @staticmethod
    def _safe_autonomy_mode(value: Any) -> str:
        value = str(value or AutonomyMode.SUPERVISED_AUTONOMY.value).upper()
        valid = {item.value for item in AutonomyMode}
        return value if value in valid else AutonomyMode.SUPERVISED_AUTONOMY.value

    @staticmethod
    def _safe_action_type(value: Any) -> str:
        value = str(value or ExecutionActionType.UNKNOWN.value).upper()
        valid = {item.value for item in ExecutionActionType}
        return value if value in valid else ExecutionActionType.UNKNOWN.value

    @staticmethod
    def _safe_domain(value: Any) -> str:
        value = str(value or AlignmentDomain.UNKNOWN.value).upper()
        valid = {item.value for item in AlignmentDomain}
        return value if value in valid else AlignmentDomain.UNKNOWN.value

    @staticmethod
    def _safe_severity(value: Any) -> str:
        value = str(value or SEVERITY_INFO).upper()
        valid = {
            SEVERITY_INFO,
            SEVERITY_LOW,
            SEVERITY_MEDIUM,
            SEVERITY_HIGH,
            SEVERITY_CRITICAL,
        }
        return value if value in valid else SEVERITY_INFO

    @staticmethod
    def _clamp_confidence(value: Any) -> float:
        try:
            score = float(value)
        except Exception:
            score = 0.0

        return max(0.0, min(1.0, score))


# ============================================================
# FACTORY
# ============================================================

def build_sovereign_execution_alignment_engine(
    *,
    autonomy_mode: str = AutonomyMode.SUPERVISED_AUTONOMY.value,
    event_bus: Optional[Any] = None,
    operational_memory_engine: Optional[Any] = None,
    governance_engine: Optional[Any] = None,
    lineage_engine: Optional[Any] = None,
    continuity_engine: Optional[Any] = None,
) -> SovereignExecutionAlignmentEngine:
    """
    Factory for explicit dependency injection.
    """

    return SovereignExecutionAlignmentEngine(
        autonomy_mode=autonomy_mode,
        event_bus=event_bus,
        operational_memory_engine=operational_memory_engine,
        governance_engine=governance_engine,
        lineage_engine=lineage_engine,
        continuity_engine=continuity_engine,
    )